# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
