# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('w_menu', '0004_auto_20171206_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_menu.Dish', verbose_name='Dish')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='w_menu.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'DishComposition',
                'verbose_name_plural': 'DishCompositions',
            },
        ),
    ]
