# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_menu', '0005_dishcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, unique=True, verbose_name='title')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='recipe'),
        ),
    ]
