# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w_menu', '0006_auto_20171218_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdeleted',
            options={'verbose_name': 'DeletedProduct', 'verbose_name_plural': 'DeletedProducts'},
        ),
        migrations.AlterField(
            model_name='productdeleted',
            name='title',
            field=models.CharField(blank=True, max_length=256, verbose_name='title'),
        ),
    ]
